//
//  StoryPromoStyle.swift
//
//
//  Created by Bilaal Rashid on 26/05/2024.
//

import Foundation

public enum StoryPromoStyle: String, Codable, Equatable, Hashable, Unknownable {

}

- LARGE_PROMO_CARD
- SMALL_CAROUSEL_PROMO_CARD
- SMALL_HORIZONTAL_PROMO_CARD
- SMALL_VERTICAL_PROMO_CARD
- VIDEO_PACKAGE_PROMO_CARD
- BADGE_LED_PROMO_CARD
- EMPHASISED_PROMO_CARD
- GALLERY_PROMO_CARD
- HERO_PROMO_CARD
- HIGHLIGHTED_PROMO_CARD
- IMAGE_LED_PROMO_CARD
- IMPACTFUL_TEXT_PROMO_CARD
- LARGE_PROMO_CARD
- PORTRAIT_PROMO_CARD
- SMALL_CAROUSEL_PROMO_CARD
- SMALL_HORIZONTAL_PROMO_CARD
- SMALL_VERTICAL_PROMO_CARD
- SQUARE_PROMO_CARD
- SQUARE_TEXT_OVER_IMAGE_PROMO_CARD
- TEXT_PROMO_CARD
- VIDEO_PACKAGE_PROMO_CARD
