name: SwiftLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:5.5-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: SwiftLint
      run: |
        swiftlint --reporter github-actions-logging --strict
