name: SwiftLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: SwiftLint
      run: |
        swiftlint --config .swiftlint.yml --reporter github-actions-logging --strict
