name: OpenAPI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Run linting
        run: redocly lint openapi/*/openapi.yaml --format=github-actions

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      - name: Create output directory
        run: mkdir -p build

      - name: Build pre-5
        run: redocly build-docs openapi/pre-5/openapi.yaml --output build/pre-5.html

      - name: Build pre-6
        run: redocly build-docs openapi/pre-5/openapi.yaml --output build/pre-6.html

      - name: Build pre-7
        run: redocly build-docs openapi/pre-7/openapi.yaml --output build/pre-7.html

      - name: Link index.html to latest version
        run: cp build/pre-7.html build/index.html

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
